AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Ilios LTI Server.
  Creates endpoints for authenticating and serving the Dashboard and Course Management LTI
  iframe response.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
  Api:
    OpenApiVersion: 3.0.1 #meaningless workaround, see https://github.com/aws/serverless-application-model/issues/3447#issuecomment-1828702747

Parameters:
  StageName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: The stage for this stack
  LtiDashboardURL:
    Type: String
    Description: The URL to redirect the user to with their authentication token

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
  DashboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.dashboardHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          CONFIG_BUCKET: !Ref ConfigBucket
          DASHBOARD_APP_URL: !Ref LtiDashboardURL
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ConfigBucket
      Events:
        Payload:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /dashboard
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/client-s3"
  PayloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.payloadHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        Payload:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /payload
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/client-s3"
  ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-launch-configuration'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DashboardApi:
    Description: "API Gateway endpoint URL for Prod stage for Dashboard function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/dashboard/"
  DashboardFunction:
    Description: "Dashboard Lambda Function ARN"
    Value: !GetAtt DashboardFunction.Arn
  DashboardFunctionIamRole:
    Description: "Implicit IAM Role created for Dashboard function"
    Value: !GetAtt PayloadFunctionRole.Arn
  PayloadApi:
    Description: "API Gateway endpoint URL for Prod stage for Payload function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/payload/"
  PayloadFunction:
    Description: "Payload Lambda Function ARN"
    Value: !GetAtt PayloadFunction.Arn
  PayloadFunctionIamRole:
    Description: "Implicit IAM Role created for Payload function"
    Value: !GetAtt PayloadFunctionRole.Arn
