AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Ilios LTI Server.
  Creates endpoints for authenticating and serving the Dashboard and Course Management LTI
  iframe response.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  PayloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/
      Handler: app.payloadHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        Payload:
          Type: Api
          Properties:
            Path: /payload
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PayloadApi:
    Description: "API Gateway endpoint URL for Prod stage for Payload function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/payload/"
  PayloadFunction:
    Description: "Payload Lambda Function ARN"
    Value: !GetAtt PayloadFunction.Arn
  PayloadFunctionIamRole:
    Description: "Implicit IAM Role created for Payload function"
    Value: !GetAtt PayloadFunctionRole.Arn
