name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request: {}
  schedule:
    - cron: "52 5 * * 6" # weekly, on Saturday morning

jobs:
  test:
    name: Lint and Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: test
        run: pnpm run test
