name: Deploy Dev Build

on:
  push:
    branches:
      - master

concurrency: deploy-dev

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: pnpm install
    - run: pnpm run test

  deploy:
    name: Deploy Lambda Function
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install dependencies
      run: pnpm install --prod
    - run: pnpm exec serverless package --stage dev
    - uses: actions/upload-artifact@v4
      with:
        name: dev-ilios-lti-launch.zip
        path: ./.serverless/ilios-lti-launch.zip
        if-no-files-found: error
        retention-days: 3
        compression-level: 0
    - run: pnpm exec serverless deploy --stage dev --package ./.serverless/ilios-lti-launch.zip --conceal
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - uses: act10ns/slack@v2
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ILIOS_DEPLOYMENT_WEBHOOK_URL }}
      with:
        status: ${{ job.status }}
        message: LTI Server deploy failed {{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID }}

